using HRMS.Web.Models.DataModels;
using HRMS.Web.Respostories.Common;

namespace HRMS.Web.Respostories.Domain {
    public interface IPositoryRepository : IBaseRepository<PositionEntity> {
        //specification implemenation in here 
        //new implemenation in here 
        ///see more .....................................................
        ///............................................
        ///....................................................
        ///..................................................
    }
}
