Use HRMS;
create Table Employee(
Id char(36) Primary Key,
Code nvarchar(255) Not Null,
[Name] nvarchar(255) Not Null,
[Email] char(255) Not Null,
Gender char(1) NOT NULL,
DOB datetime not null,
DOE Datetime not null,
DOR datetime ,
[Address] text,
BasicSalary decimal(18,2) NOT NULL,
Phone nvarchar(255),
DepartmentId char(36) NOT NULL,
PositionId char(36) NOT NULL,
CreatedAt DateTime Not Null,
CreatedBy char(36) Not NUll,
UpdatedAt DateTime,
UpdatedBy char(36),
[Ip] char(255) Not Null,
IsActive bit Not Null ,
constraint fk_department_employee foreign key (DepartmentId) references Department(Id),
constraint fk_position_employee foreign key (PositionId) references Position(Id),
);